#include "avz_multi_platform.h"
#include FILE_ORIGINAL(libavz.h)


#include FILE_ORIGINAL(avz_asm.cpp)
#include FILE_ORIGINAL(avz_card.cpp)
#include FILE_ORIGINAL(avz_click.cpp)
#include FILE_ORIGINAL(avz_cob_manager.cpp)
#include FILE_ORIGINAL(avz_connector.cpp)
#include FILE_ORIGINAL(avz_coroutine.cpp)
#include FILE_ORIGINAL(avz_game_controllor.cpp)
#include FILE_ORIGINAL(avz_hook.cpp)
#include FILE_ORIGINAL(avz_logger.cpp)
#include FILE_ORIGINAL(avz_memory.cpp)
#include FILE_ORIGINAL(avz_painter.cpp)
#include FILE_ORIGINAL(avz_replay.cpp)
#include FILE_ORIGINAL(avz_script.cpp)
#include FILE_ORIGINAL(avz_smart.cpp)
#include FILE_ORIGINAL(avz_tick_runner.cpp)
#include FILE_ORIGINAL(avz_time_queue.cpp)
